# Generated by Django 5.1.1 on 2024-09-09 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], max_length=200)),
                ('loan_start_date', models.DateField(default=django.utils.timezone.now)),
                ('loan_end_date', models.DateField()),
                ('loan_period', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.FileField(upload_to='client/ID')),
                ('pin_file', models.FileField(upload_to='client/PIN')),
                ('offer_letter', models.FileField(upload_to='client/offer-letters')),
                ('tracking_certificate', models.FileField(upload_to='tracking/certificate')),
                ('tracking_invoice', models.FileField(upload_to='tracking/invoice')),
                ('tracking_vendor', models.FileField(upload_to='tracking/vendors')),
                ('insurance_certificate', models.FileField(upload_to='other/insurance-certificates')),
                ('loan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
