# Generated by Django 5.1.1 on 2024-09-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.bank'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
