# Generated by Django 5.1.1 on 2024-09-11 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_bank_alter_loan_loan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requirements', to='loan.loan'),
        ),
    ]
