# Generated by Django 5.1.1 on 2024-09-11 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_loan_id_alter_loanrequirement_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
