# Generated by Django 5.1.1 on 2024-09-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_loan_end_date_alter_loan_loan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_batch_number',
            field=models.IntegerField(default=1),
        ),
    ]
