# Generated by Django 5.1.1 on 2024-09-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('loan', '0001_initial'),
        ('remedial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=100)),
                ('make_and_model', models.CharField(max_length=200)),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chasis', models.CharField(max_length=200)),
                ('dealer', models.CharField(max_length=200)),
                ('tracking_status', models.CharField(max_length=200)),
                ('asset_type', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=100)),
                ('insurance_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('engine', models.CharField(max_length=100)),
                ('asset_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('remedial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remedial.remedial')),
            ],
        ),
    ]
