# Generated by Django 5.1.1 on 2024-09-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('clients', '0001_initial'),
        ('loan', '0002_bank'),
        ('remedial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetregister',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='assetregister',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='assetregister',
            name='remedial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remedial.remedial'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_status'], name='asset_asset_asset_s_be9797_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['vehicle_reg_no'], name='asset_asset_vehicle_095cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['make_and_model'], name='asset_asset_make_an_567141_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tracking_status'], name='asset_asset_trackin_de5ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['vehicle_reg_no', 'tracking_status', 'asset_status', 'make_and_model'], name='asset_asset_vehicle_77cb16_idx'),
        ),
    ]
