# Generated by Django 5.1.1 on 2024-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('id_number', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('PIN_number', models.CharField(max_length=50)),
            ],
        ),
    ]
